services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"

  activemq:
    image: apache/activemq-classic:latest
    restart: unless-stopped
    ports:
      - "61616:61616"
      - "8161:8161"