server:
  port: 8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: product-query-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
            - Method=GET # Since Query from CQRS only uses GET Method

        - id: product-command-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**

        - id: stock-command-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/stocks/**