server:
  port: 8082

spring:
  application:
    name: ProductCommandService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-command
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
